"""empty message

Revision ID: 1e72ecf7e3dd
Revises: 31813edde0fe
Create Date: 2015-02-07 14:17:58.796936

"""

# revision identifiers, used by Alembic.
revision = '1e72ecf7e3dd'
down_revision = '31813edde0fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('text', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'text')
    ### end Alembic commands ###
