"""empty message

Revision ID: 215f0351d446
Revises: 598562686e8
Create Date: 2015-02-20 17:27:57.952276

"""

# revision identifiers, used by Alembic.
revision = '215f0351d446'
down_revision = '598562686e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_item',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.add_column(u'item', sa.Column('voteSum', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'item', 'voteSum')
    op.drop_table('user_item')
    ### end Alembic commands ###
