"""empty message

Revision ID: 2500076b8d10
Revises: 199c46fe7acd
Create Date: 2015-02-15 15:19:16.976874

"""

# revision identifiers, used by Alembic.
revision = '2500076b8d10'
down_revision = '199c46fe7acd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'mergeable')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('mergeable', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
