"""empty message

Revision ID: 293250007b39
Revises: 2ad0f09d35de
Create Date: 2015-05-06 23:36:46.124319

"""

# revision identifiers, used by Alembic.
revision = '293250007b39'
down_revision = '2ad0f09d35de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=50), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_column('topic')

    ### end Alembic commands ###
