"""empty message

Revision ID: 2c91f85d15ab
Revises: 1e72ecf7e3dd
Create Date: 2015-02-11 16:39:11.599893

"""

# revision identifiers, used by Alembic.
revision = '2c91f85d15ab'
down_revision = '1e72ecf7e3dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_1', sa.String(length=100), nullable=True))
    op.add_column('item', sa.Column('category_2', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'category_2')
    op.drop_column('item', 'category_1')
    ### end Alembic commands ###
