"""empty message

Revision ID: 356c2d8bc34
Revises: 3df22bce9ff4
Create Date: 2015-02-03 15:58:36.453067

"""

# revision identifiers, used by Alembic.
revision = '356c2d8bc34'
down_revision = '3df22bce9ff4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
