"""empty message

Revision ID: 3f88c0fba1fe
Revises: 2c91f85d15ab
Create Date: 2015-02-11 18:27:38.853274

"""

# revision identifiers, used by Alembic.
revision = '3f88c0fba1fe'
down_revision = '2c91f85d15ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_link', table_name='item')
    op.create_index(op.f('ix_item_link'), 'item', ['link'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_link'), table_name='item')
    op.create_index('ix_item_link', 'item', ['link'], unique=1)
    ### end Alembic commands ###
