"""empty message

Revision ID: 4044103c9a9c
Revises: 51e9a3f84285
Create Date: 2015-05-31 22:12:44.845332

"""

# revision identifiers, used by Alembic.
revision = '4044103c9a9c'
down_revision = '51e9a3f84285'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_suggested_content', sa.Boolean(), nullable=True))
        batch_op.drop_column('show_unsubscribed_content')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_unsubscribed_content', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('show_suggested_content')

    ### end Alembic commands ###
