"""empty message

Revision ID: 426f1ad50ca2
Revises: 598562686e8
Create Date: 2015-02-18 15:46:44.779144

"""

# revision identifiers, used by Alembic.
revision = '426f1ad50ca2'
down_revision = '598562686e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column(u'item', sa.Column('totalVotes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'item', 'totalVotes')
    op.drop_table('items_users')
    ### end Alembic commands ###
