"""empty message

Revision ID: 47428d5169d3
Revises: 518377732728
Create Date: 2015-04-18 18:51:59.957365

"""

# revision identifiers, used by Alembic.
revision = '47428d5169d3'
down_revision = '518377732728'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_category_category'), 'category', ['category'], unique=True)

    op.create_table('categories',
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], )
    )
    with op.batch_alter_table(u'item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_link'))
        batch_op.add_column(sa.Column('categorized', sa.Boolean(), nullable=True))
        batch_op.drop_column('category_2')
        batch_op.drop_column('category_1')
    op.create_index(batch_op.f('ix_item_link'), 'item', ['link'])


    with op.batch_alter_table(u'user_item', schema=None) as batch_op:
        batch_op.drop_column('category_2')
        batch_op.drop_column('category_1')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'user_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_1', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('category_2', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table(u'item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_link'))
        batch_op.add_column(sa.Column('category_1', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('category_2', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('categorized')
    op.create_index(batch_op.f('ix_item_link'), 'item', ['link'])


    op.drop_table('categories')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_category'))

    op.drop_table('category')
    ### end Alembic commands ###
