"""empty message

Revision ID: 4a2eef076e71
Revises: 598562686e8
Create Date: 2015-02-20 00:09:04.005573

"""

# revision identifiers, used by Alembic.
revision = '4a2eef076e71'
down_revision = '598562686e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.add_column(u'item', sa.Column('totalVotes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'item', 'totalVotes')
    op.drop_table('user_items')
    ### end Alembic commands ###
