"""empty message

Revision ID: 518377732728
Revises: f748d763fc8
Create Date: 2015-04-02 16:27:16.720047

"""

# revision identifiers, used by Alembic.
revision = '518377732728'
down_revision = 'f748d763fc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_item', sa.Column('last_modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_item', 'last_modified')
    ### end Alembic commands ###
