"""empty message

Revision ID: 518377732728
Revises: f748d763fc8
Create Date: 2015-04-02 16:27:16.720047

"""

# revision identifiers, used by Alembic.
revision = '518377732728'
down_revision = 'f748d763fc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item') as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item') as batch_op:
        batch_op.drop_column('last_modified')
    ### end Alembic commands ###
