"""empty message

Revision ID: 51e9a3f84285
Revises: 49086d29824
Create Date: 2015-05-18 17:04:26.183859

"""

# revision identifiers, used by Alembic.
revision = '51e9a3f84285'
down_revision = '49086d29824'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.add_column(sa.Column('show_unsubscribed_content', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('show_unsubscribed_content')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)

    ### end Alembic commands ###
