"""empty message

Revision ID: 56178488a40
Revises: 599a83ea64d
Create Date: 2015-02-25 13:32:44.177514

"""

# revision identifiers, used by Alembic.
revision = '56178488a40'
down_revision = '599a83ea64d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_item', sa.Column('unread', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_item', 'unread')
    ### end Alembic commands ###
