"""empty message

Revision ID: 599a83ea64d
Revises: 215f0351d446
Create Date: 2015-02-21 22:15:13.030925

"""

# revision identifiers, used by Alembic.
revision = '599a83ea64d'
down_revision = '215f0351d446'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_url', sa.String(length=400), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image_url')
    ### end Alembic commands ###
