"""empty message

Revision ID: f748d763fc8
Revises: 33486673c93e
Create Date: 2015-03-04 16:04:57.476786

"""

# revision identifiers, used by Alembic.
revision = 'f748d763fc8'
down_revision = '33486673c93e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('feed', sa.Column('image_url', sa.String(length=400), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'image_url')
    op.drop_column('feed', 'description')
    ### end Alembic commands ###
