"""empty message

Revision ID: fe950bb8623
Revises: 3f88c0fba1fe
Create Date: 2015-02-11 18:39:19.002318

"""

# revision identifiers, used by Alembic.
revision = 'fe950bb8623'
down_revision = '3f88c0fba1fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
